### ISSUE TITLE
Windows Defender scans this as a possible PUP

### ISSUE THREAD

**Issue by super-toy1** [FlyTechVideos/BluescreenSimulator#103]
If you don't know what PUP stands for in the technical world, it stands for Potentially Unwanted Program. Can you please fix this in the future when possible?

**Comment by super-toy1** [comment]
What Windows Defender scanned was Program:Win32/Uwamson.A!ml

**Comment by SamyoFox** [comment]
That is a false-positive.

**Comment by Velcro3** [comment]
wtf?

**Comment by Flytechfan101** [comment]
That happened with me. Heres how to disable it.
1. Open WS. (Windows Security).
2. Go to "App and Browser Control".
3. Click "Reputation based protection settings".
4. Disable "Check apps and files" to disable.
              -THIS IS AT YOUR OWN RISK-

**Comment by n0b0py** [comment]
That happened to me too, first time it was scanned as "Joke:Win32/ScreenMate" and it was from "C:\Users\Home\Desktop\testing\BluescreenSimulator.exe". The second time it was "Program:Win32/Uwamson.A!ml" from "C:\Users\Home\Downloads\BluescreenSimulator.exe", ScreenMate was scanned as Moderate and Uwamson was scanned as low. Before I got the messages, I made a executable file for it and called it "tenu", but it was detected by Windows Defender as "Trojan:Script/Wacatac.B!ml" from "C:\Users\Home\Desktop\tenu.exe", Windows detected it as Severe, most likely because it opens a fullscreen window that you cant Alt+F4 or Alt+Tab out of, and windows does NOT know that F7 closes it, so Windows thinks its bad and its to stop users from doing anything.

**Comment by Flytechfan101** [comment]
Well Windows is wrong. Use MacOS or Linux lol.

**Comment by n0b0py** [comment]
Well cant you just click on the message and press "Allow on device"?

**Comment by 0xRoco** [comment]
this is a false positive.
Use the search field before making an issue.
[VirusTotal scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
