### ISSUE TITLE
Hanging in the end

### ISSUE THREAD

**Issue by Oleksii-Kryzhanivksyi** [FlyTechVideos/BluescreenSimulator#106]
At the end of loading (100% complete), it just hung. I couldn't see my mouse, and I couldn't bring up Task Manager (actually, Task Manager just appeared **below** the fullscreen "BSoD")+I couldn't take a screenshot. I have restarted my computer using Ctrl+Alt+Del. Is "100% complete" -> "end" transition long or a bug?

**Comment by FlyTechVideos** [comment]
The transition should have been no more than 3 seconds. It is now configurable, either way, the fact that it didn't close should not have happened. But maybe this bug is fixed in the latest version, so please give it a try (and if it doesn't work, feel free to reopen this issue)

https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
