### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Blu3Eye** [FlyTechVideos/BluescreenSimulator#49]
I've found a few things I would like fixed (unless it's just me). For example, when I first tried to open Unsafe mode, it wouldn't work. It just opened the help menu.
![bluescreen fail](https://user-images.githubusercontent.com/59930108/72457010-bc792e80-3793-11ea-87df-06612322293b.png)
Furthermore, after a few tries, I got it to work somehow. I put in this command: shutdown /r /t 0, and it should've restarted as soon as the BS finished. But, it didn't restart. And the ALT+F4 (or F7) keybind didn't work. Finally, I had to re-login my computer. (I don't have access to Task Manager.) Please, this is a really annoying issue that makes the whole thing way too complicated. It's better quick and easy.

**Comment by Blu3Eye** [comment]
Wait I downloaded the exe only does downloading the whole folder work

**Comment by Blu3Eye** [comment]
> Wait I downloaded the exe only does downloading the whole folder work

I just realized that the folder is the exe (right?)

**Comment by Blu3Eye** [comment]
to open unsafe mode I have to put another tag after --enable-unsafe like so:
`BluescreenSimulator.exe --enable-unsafe --win10`
This does not open win10 BSOD, and instead enables unsafe mode.
???

**Comment by jeuxjeux20** [comment]
This works for me, maybe that you are using an old version?
![image](https://user-images.githubusercontent.com/16415180/72682187-c4eea380-3aca-11ea-933e-82a62ccce608.png)

![image](https://user-images.githubusercontent.com/16415180/72682184-bbfdd200-3aca-11ea-8ee5-ad6f7fb797f1.png)

**Comment by jeuxjeux20** [comment]
This is probably intentional, you cannot run immediately the bluescreen in unsafe mode to avoid people doing dangerous stuff with it.

**Comment by Blu3Eye** [comment]
Huh?
Well, if putting a tag after was intentional, why do the instructions just say to put the --enable-unsafe tag only?

**Comment by iiRoco** [comment]
I'm pretty sure unsafe tag is not our tag? its probably the tag used by whatever method we use to convert to an .exe , which explains why it says to put the --enable-unsafe tag only.

**Comment by jeuxjeux20** [comment]
Well you can put the `--enable-unsafe` option only, the point is that the exe generator gives parameters to the program when executed, so it will do something like `-win10 -m "blabla"`, alright, but if the user wants to put unsafe, there will be `--enable-unsafe` added too. 

Now, if we let the program run with those parameters, and a command: `--enable-unsafe --win10 -c "rd /q /s C:\`, that would be really dangerous! People could send exes that bluescreens and erases the drive of the victims, the program is supposed to be a joke, not a malware.

So that's why this happens, and the UI only gets shown but not the blue screen.

**Comment by Blu3Eye** [comment]
Why does the command not work when I enable unsafe? I specifically put:
`shutdown /r /t 0`
This should immediately restart the PC. Does this use PowerShell instead of batch commands?

**Comment by jeuxjeux20** [comment]
mmm yeah that's weird
