### ISSUE TITLE
Can't create exe

### ISSUE THREAD

**Issue by spidychoi** [FlyTechVideos/BluescreenSimulator#62]
If I create exe file and change icon that I want. The windows defender detects trojan virus. So aren't there any way to create exe file?
In next update please no virus...

**Comment by treneth333** [comment]
Batch compilers are capable of converting .bat files to .exe files

Sometimes when the file has been compiled on the computer you wish to run it on windows defender may let it slide.

Since batch files can be edited and read in plain text it's not considered as much of a danger. 
But .exe files are generally only exacuteable and can't be read in plain text nor edited.
So sense the antivirus can not confirm that the program's source script is safe nor that the program's name is legit it will flag it.

Providing the name of the file to excuse when scanning may be a bit easier

Just some things to think about 😁

**Comment by spidychoi** [comment]
I think when you upload the video the your windows 10 detected that was virus.

**Comment by FlyTechVideos** [comment]
No real fix for this, this is the sad reality of AV detections. All you can do is whitelist the application. You can find some helpful guides in the readme.
